.TH GDLEX-GUI 1 "May 2026" "gdlex-pct-validator 1.2.1" "User Commands"
.SH NAME
gdlex-gui \- avvia la GUI del validatore PCT/PDUA GD LEX
.SH SYNOPSIS
.B gdlex-gui
.SH DESCRIPTION
.B gdlex-gui
avvia l'interfaccia grafica di GD LEX PCT Validator per la verifica
di depositi PCT/PDUA e la generazione dei relativi report tecnici.
.SH OPTIONS
Il comando non documenta opzioni da riga di comando aggiuntive.
.SH FILES
.TP
.I /usr/bin/gdlex-gui
Launcher della GUI installato dal pacchetto Debian.
.TP
.I /usr/lib/gdlex-pct-validator
Directory applicativa installata dal pacchetto.
.SH AUTHOR
Studio GD LEX <info@studiogdlex.it>
.SH COPYRIGHT
Copyright \(co 2026 Studio GD LEX.
Licenza GPL-3.0-or-later.
